const menu = {
  Pichangas: [{name:'Pichangas', price:7500},{name:'Pichangas', price:10500},{name:'Pichangas', price:11500},{name:'Pichangas', price:13500},{name:'Pichangas', price:19500}],
  Completos: [{name:'Dinámico', price:2500},{name:'Italiano', price:2500},{name:'Especial palta', price:2800},{name:'Hass pollo o carne', price:4000},{name:'Hass Mixto', price:4000},{name:'Hass loco', price:4000}],
  'Salchipollo o carne': [{name:'Salchipollo o carne', price:7000},{name:'Salchipollo o carne', price:9000},{name:'Salchipollo o carne', price:11000},{name:'Salchipollo o carne', price:13000}],
  Churrascos: [{name:'Italiano', price:6500},{name:'Barro Luco', price:5500},{name:'Tortuga', price:3500},{name:'Churrasco palta', price:6000},{name:'Brasileño', price:5500},{name:'Chacarero', price:7000},{name:'Churrasco solo', price:5000}],
  Salchipapas: [{name:'Salchipapas', price:3000},{name:'Salchipapas', price:4500},{name:'Salchipapas', price:6500},{name:'Salchipapas', price:8500}],
  Chorrillanas: [{name:'Chorrillana', price:8000},{name:'Chorrillana', price:12000},{name:'Chorrillana', price:15000}],
  'Papa sola': [{name:'Papa sola', price:2500},{name:'Papa sola', price:3500},{name:'Papa sola', price:4500},{name:'Papa sola', price:8500}],
  Salchiqueso: [{name:'Salchiqueso', price:6500},{name:'Salchiqueso', price:7500},{name:'Salchiqueso', price:8500},{name:'Salchiqueso', price:13500}],
  'Pichangas con camarón': [{name:'Pichangas con camarón', price:11500},{name:'Pichangas con camarón', price:13500},{name:'Pichangas con camarón', price:16500},{name:'Pichangas con camarón', price:21000}],
  Pailas: [{name:'Paila · 2 huevos', price:2000},{name:'Paila · 3 huevos', price:3000},{name:'Paila · 4 huevos', price:3500},{name:'Paila · 2 huevos + 1 agregado', price:3500},{name:'Agregado · jamón o queso', price:0}]
};
const allProducts = Object.entries(menu).flatMap(([group, items]) => items.map((item, index) => ({...item, group, id:`${group}-${index}`})));
const state = { quantities: {}, drinks: 0 };
const STORAGE_KEY = 'pichangas-daily-sales';
const PENDING_DELIVERIES_KEY = 'pichangas-pending-deliveries';
const money = (value) => `$${Math.round(Number(value) || 0).toLocaleString('es-CL')}`;
const today = new Date();
const isoDate = (date) => { const local = new Date(date); local.setMinutes(local.getMinutes() - local.getTimezoneOffset()); return local.toISOString().slice(0,10); };
const prettyDate = (date) => new Date(`${date}T12:00:00`).toLocaleDateString('es-CL',{day:'2-digit',month:'short',year:'numeric'});
function getSales(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)) || [];}catch{return [];} }
function saveSales(sales){localStorage.setItem(STORAGE_KEY,JSON.stringify(sales));}
function getPendingDeliveries(){try{return JSON.parse(localStorage.getItem(PENDING_DELIVERIES_KEY))||[];}catch{return [];}}
function savePendingDeliveries(items){localStorage.setItem(PENDING_DELIVERIES_KEY,JSON.stringify(items));}
function saleTotal(sale){return sale.menuTotal+sale.drinks+sale.deliveries;}
function currentTotals(){let products=0,menuTotal=0;Object.entries(state.quantities).forEach(([id,quantity])=>{const product=allProducts.find(item=>item.id===id);if(product){products+=quantity;menuTotal+=product.price*quantity;}});const deliveries=getPendingDeliveries();const deliveryTotal=deliveries.reduce((sum,item)=>sum+item.amount,0);return {products,menuTotal,drinks:Number(state.drinks)||0,deliveries:deliveryTotal,deliveryCount:deliveries.length,total:menuTotal+(Number(state.drinks)||0)+deliveryTotal};}
function renderProducts(){document.querySelector('#product-groups').innerHTML=Object.entries(menu).map(([group,items])=>`<div class="product-group group-${group.toLowerCase().replaceAll(' ','-')}" data-group="${group}"><h4>${group}</h4>${items.map((item,index)=>{const id=`${group}-${index}`;return `<div class="sale-product"><label for="q-${id}">${item.name}<small>${item.price?money(item.price):'Precio manual'}</small></label><input class="quantity-input" id="q-${id}" data-quantity="${id}" type="number" min="0" value="${state.quantities[id]||0}"><strong class="product-subtotal" data-subtotal="${id}">${money((state.quantities[id]||0)*item.price)}</strong></div>`;}).join('')}</div>`).join('');document.querySelectorAll('[data-quantity]').forEach(input=>input.addEventListener('input',()=>{state.quantities[input.dataset.quantity]=Math.max(0,Number(input.value)||0);renderClosingSummary();}));}
function renderClosingSummary(){const totals=currentTotals();document.querySelector('#closing-products').textContent=totals.products;document.querySelector('#closing-menu').textContent=money(totals.menuTotal);document.querySelector('#closing-drinks').textContent=money(totals.drinks);document.querySelector('#closing-deliveries').textContent=money(totals.deliveries);document.querySelector('#closing-delivery-count').textContent=totals.deliveryCount;document.querySelector('#closing-total').textContent=money(totals.total);document.querySelectorAll('[data-subtotal]').forEach(el=>{const item=allProducts.find(product=>product.id===el.dataset.subtotal);el.textContent=money((state.quantities[item.id]||0)*item.price);});}
function resetClosing(){state.quantities={};state.drinks=0;document.querySelector('#drinks-input').value='';document.querySelector('#sale-note').value='';renderProducts();renderClosingSummary();}
function renderPendingDeliveries(){const items=getPendingDeliveries();const total=items.reduce((sum,item)=>sum+item.amount,0);document.querySelector('#pending-count').textContent=items.length;document.querySelector('#delivery-list-count').textContent=items.length;document.querySelector('#delivery-list-total').textContent=money(total);document.querySelector('#delivery-list').innerHTML=items.length?items.map((item,index)=>`<div class="delivery-row"><div><b>${item.name}</b><small>${money(item.amount)}</small></div><button class="remove-delivery" data-remove-delivery="${index}" aria-label="Eliminar reparto">×</button></div>`).join(''):'<p class="empty-deliveries">Todavía no hay repartos registrados.</p>';document.querySelectorAll('[data-remove-delivery]').forEach(button=>button.addEventListener('click',()=>{const next=getPendingDeliveries();next.splice(Number(button.dataset.removeDelivery),1);savePendingDeliveries(next);renderPendingDeliveries();renderClosingSummary();}));}
function getPeriodStart(period){const date=new Date();if(period==='week'){const day=date.getDay()||7;date.setDate(date.getDate()-day+1);}if(period==='month')date.setDate(1);if(period==='year'){date.setMonth(0,1);}return isoDate(date);}
function inPeriod(date,period){return date>=getPeriodStart(period)&&date<=isoDate(new Date());}
function updateDashboard(){const sales=getSales(), todaySale=sales.find(sale=>sale.date===isoDate(today)), week=sales.filter(sale=>inPeriod(sale.date,'week')), month=sales.filter(sale=>inPeriod(sale.date,'month'));document.querySelector('#summary-today').textContent=money(todaySale?saleTotal(todaySale):0);document.querySelector('#summary-orders').textContent=`${todaySale?todaySale.products:0} productos vendidos`;document.querySelector('#summary-week').textContent=money(week.reduce((sum,sale)=>sum+saleTotal(sale),0));document.querySelector('#summary-week-days').textContent=`${week.length} días registrados`;document.querySelector('#summary-month').textContent=money(month.reduce((sum,sale)=>sum+saleTotal(sale),0));document.querySelector('#summary-month-days').textContent=`${month.length} días registrados`;document.querySelector('#summary-average').textContent=money(sales.length?sales.reduce((sum,sale)=>sum+saleTotal(sale),0)/sales.length:0);renderChart(sales);renderRecent(sales);}
function renderChart(sales){const days=[];for(let i=6;i>=0;i--){const date=new Date();date.setDate(date.getDate()-i);const key=isoDate(date);const sale=sales.find(item=>item.date===key);days.push({key,label:date.toLocaleDateString('es-CL',{weekday:'short'}).replace('.',''),value:sale?saleTotal(sale):0});}const max=Math.max(...days.map(day=>day.value),1);document.querySelector('#week-chart').innerHTML=days.map(day=>`<div class="bar-column"><span class="bar-value">${day.value?money(day.value):''}</span><div class="bar ${day.key===isoDate(today)?'today':''}" style="height:${Math.max(day.value/max*140,3)}px"></div><span class="bar-day">${day.label}</span></div>`).join('');}
function renderRecent(sales){const rows=sales.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);document.querySelector('#recent-sales').innerHTML=rows.length?rows.map(sale=>`<div class="recent-row"><b>${prettyDate(sale.date)}</b><span class="sale-date">${sale.products} productos</span><strong class="sale-amount">${money(saleTotal(sale))}</strong><span class="sale-badge">Guardado</span></div>`).join(''):'<p class="muted">Todavía no hay cierres guardados.</p>';}
function renderReport(period='week'){const sales=getSales().filter(sale=>inPeriod(sale.date,period)).sort((a,b)=>b.date.localeCompare(a.date));const total=sales.reduce((sum,sale)=>sum+saleTotal(sale),0);const products=sales.reduce((sum,sale)=>sum+sale.products,0);const best=sales.slice().sort((a,b)=>saleTotal(b)-saleTotal(a))[0];document.querySelector('#report-total').textContent=money(total);document.querySelector('#report-days').textContent=`${sales.length} días registrados`;document.querySelector('#report-products').textContent=products;document.querySelector('#report-best').textContent=money(best?saleTotal(best):0);document.querySelector('#report-best-date').textContent=best?prettyDate(best.date):'Sin datos';document.querySelector('#report-rows').innerHTML=sales.length?sales.map(sale=>`<div class="report-row"><b>${prettyDate(sale.date)}</b><span class="sale-date">Menú ${money(sale.menuTotal)} · Bebidas ${money(sale.drinks)}</span><strong class="sale-amount">${money(saleTotal(sale))}</strong><span class="sale-badge">${sale.products} uds.</span></div>`).join(''):'<p class="muted">No hay cierres en este periodo.</p>';}
function switchView(view){document.querySelectorAll('.view').forEach(item=>item.classList.remove('active-view'));document.querySelector(`#view-${view}`).classList.add('active-view');document.querySelectorAll('.nav-link').forEach(item=>item.classList.toggle('active',item.dataset.view===view));document.querySelector('#page-title').textContent=view==='resumen'?'Resumen del negocio':view==='cierre'?'Cierre diario':view==='repartos'?'Repartos del día':'Reportes';if(view==='resumen')updateDashboard();if(view==='repartos')renderPendingDeliveries();if(view==='cierre')renderClosingSummary();if(view==='reportes')renderReport();window.scrollTo({top:0,behavior:'smooth'});}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600);}
document.querySelectorAll('[data-view],[data-view-link]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view||button.dataset.viewLink)));
document.querySelector('#sale-date').value=isoDate(today);document.querySelector('#drinks-input').addEventListener('input',event=>{state.drinks=event.target.value;renderClosingSummary();});document.querySelector('#delivery-form').addEventListener('submit',event=>{event.preventDefault();const items=getPendingDeliveries();items.push({name:document.querySelector('#delivery-name').value.trim(),amount:Number(document.querySelector('#delivery-amount').value)||0});savePendingDeliveries(items);event.currentTarget.reset();renderPendingDeliveries();renderClosingSummary();toast('Reparto agregado a la lista');});document.querySelector('#clear-deliveries').addEventListener('click',()=>{savePendingDeliveries([]);renderPendingDeliveries();renderClosingSummary();});document.querySelector('#reset-quantities').addEventListener('click',resetClosing);document.querySelector('#save-sale').addEventListener('click',()=>{const date=document.querySelector('#sale-date').value;const totals=currentTotals();if(!date){toast('Selecciona una fecha');return;}if(!totals.products&&!totals.drinks&&!totals.deliveries){toast('Ingresa al menos una venta');return;}const sales=getSales().filter(sale=>sale.date!==date);sales.push({...totals,date,note:document.querySelector('#sale-note').value});saveSales(sales);savePendingDeliveries([]);renderPendingDeliveries();toast('Cierre guardado y repartos reiniciados');updateDashboard();switchView('resumen');});document.querySelectorAll('.period-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.period-tab').forEach(item=>item.classList.remove('active'));tab.classList.add('active');renderReport(tab.dataset.period);}));document.querySelector('#export-report').addEventListener('click',()=>{const rows=getSales().map(sale=>`${sale.date};${sale.products};${sale.menuTotal};${sale.drinks};${sale.deliveries};${sale.deliveryCount||0};${saleTotal(sale)}`);const blob=new Blob([`Fecha;Productos;Menu;Bebidas;Repartos;Cantidad repartos;Total\n${rows.join('\n')}`],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='reporte-pichangas.csv';link.click();URL.revokeObjectURL(link.href);});
renderProducts();renderPendingDeliveries();renderClosingSummary();updateDashboard();
